apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: python-app-deployment
  template:
    metadata:
      labels:
        name: python-app-deployment
    spec:
      containers:
        - name: python-app-container
          image: gcr.io/amr-1-377214/python-app
          ports:
            - containerPort: 8000
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379
