apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-dep
  template:
    metadata:
      labels:
        name: app-dep
    spec:
      containers:
        - name: app-dep-container
          image: gcr.io/amr-1-377214/python-app
          ports:
            - containerPort: 8000
        - name: redis-cont
          image: redis
          ports:
            - containerPort: 6379
