apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer
  selector:
    name: python-app-deployment
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
